name: internsforyou
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  #Form Builder & Validation Packages
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.2.0
  flutter_svg: ^0.22.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  smooth_page_indicator: ^1.0.0+2 
  parse_server_sdk_flutter: ^3.1.0
  image_picker: ^0.8.5+3
  introduction_screen: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/
    - assets/images/

  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/robotorobotoromanbold700.ttf
          weight: 700
        - asset: assets/fonts/robotoregular400.ttf
          weight: 400
        - asset: assets/fonts/robotorobotoromanmedium500.ttf
          weight: 500
    - family: Roboto Condensed
      fonts: 
        - asset: assets/fonts/robotocondensedlight300.ttf
          weight: 300
        - asset: assets/fonts/robotocondensedlightitalic300.ttf
          weight: 300
        - asset: assets/fonts/robotocondensedbold700.ttf
          weight: 700
    - family: RobotoRegular
      fonts:
        - asset: lib/theme/fonts/Roboto-Regular.ttf
    - family: RobotoThin
      fonts:
        - asset: lib/theme/fonts/Roboto-Thin.ttf
    - family: RobotoCondensed
      fonts:
        - asset: lib/theme/fonts/RobotoCondensed-Regular.ttf